//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace elanora.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("elanora.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anasayfa.
        /// </summary>
        internal static string anasayfamenu {
            get {
                return ResourceManager.GetString("anasayfamenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arşiv.
        /// </summary>
        internal static string arsivmenu {
            get {
                return ResourceManager.GetString("arsivmenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merhaba, ben elanora dünyama hoşgeldiniz..
        /// </summary>
        internal static string giris {
            get {
                return ResourceManager.GetString("giris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ben Kimim....
        /// </summary>
        internal static string hakkimdaicarik2 {
            get {
                return ResourceManager.GetString("hakkimdaicarik2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merhabalar ben elanora aslen Elanur Alganatay.
        ///                    1997 Erzincan doğumlu teknolojiye aşık, ultra cins(kendimce) birisiyim.
        ///                    2011-2015 yılları arasında okuduğum Yakacık Teknik Ve Endüstri Meslek Lisesinden mezun olur olmaz direk geçiş hakkımı kullanarak Sakarya Üniversitesi Karasu Meslek Yüksek Okulu Bilgisayar Programcılığı bölümüne yerleştim ve 2017 yılında mezun oldum.
        ///                    Zaten bu alanda ilerlemek isterken bu 2 yıllık eğitimde aslında doğru yerde oldu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string hakkimdaicerik {
            get {
                return ResourceManager.GetString("hakkimdaicerik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hakkımda.
        /// </summary>
        internal static string hakkimdamenu {
            get {
                return ResourceManager.GetString("hakkimdamenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bana Ulaşmak İçin....
        /// </summary>
        internal static string iletisimicerik {
            get {
                return ResourceManager.GetString("iletisimicerik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İletişim.
        /// </summary>
        internal static string iletisimmenu {
            get {
                return ResourceManager.GetString("iletisimmenu", resourceCulture);
            }
        }
    }
}
